### PR TITLE
refactor: remove ineffective export keywords

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
These keywords are only ineffective in Deno. The last time I tried, it was required to export the interfaces inside exported modules, too, when the project is compiled to `.d.ts` files. Closing. Feel free to reopen if you try this and determine that things have changed.

**Comment by roj1512** [comment]
Screenshot 2023-12-31 at 09 54 22

**Comment by KnorpelSenf** [comment]
Okay but can you use them in your node project now?

**Comment by roj1512** [comment]
Screenshot 2023-12-31 at 18 30 51

**Comment by KnorpelSenf** [comment]
Not inside this package, inside a separate project that imports things which need to be resolved via `package.json`

**Comment by KnorpelSenf** [comment]
Largely outdated and still untested

**Pull request closed without merging**
