### PR TITLE
Clarifications to the deleteMessage() call

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by roj1512** [comment]
I think users, too, cannot delete messages older than 48 hours, not just bots.

**Comment by dilyanpalauzov** [comment]
On the channels I have created, I can delete older messages.

**Comment by roj1512** [comment]
Bots can delete channel posts older than 48 hours, too, can't they? The 48 hours case is only for groups and private chats.

**Comment by dilyanpalauzov** [comment]
> Bots can delete channel posts older than 48 hours, too, can't they?

No, they cannot .  I have tried and it does not work, therefore I propose updating the documentation to the actual behaviour.

**Comment by KnorpelSenf** [comment]
These are not our docs. They're extracted from https://core.telegram.org/bots/api#deletemessage and I'd prefer to keep things perfectly in sync.

**Comment by KnorpelSenf** [comment]
If you think something is wrong, you can contact `@levlam` in https://t.me/tdlibchat.

**Comment by KnorpelSenf** [comment]
Rejected in the discussion starting at https://t.me/tdlibchat/34770

**Pull request closed without merging**
