### PR TITLE
fix: no-namespace lint rule

### PR DESCRIPTION
**Pull request by dcdunkan**

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Thanks!

**Comment by KnorpelSenf** [comment]
Waiting for one more second opinion

**Comment by dcdunkan** [comment]
> Waiting for one more second opinion

Of course. I really need one too, because I'm not sure about this entirely.

**Review by wojpawlik — APPROVED** [review]

**Review by EdJoPaTo — APPROVED** [review]
because of some older packages not updated on npm yet I still have the v2 version as a dependency sometimes. Other than that it seems to compile just fine with this change.

**Pull request merged**
