### PR TITLE
feat: narrow message updates

### PR DESCRIPTION
**Pull request by KnorpelSenf**
As announced in https://t.me/grammyjs/100772

### CODE REVIEW

**Review by MKRhere — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
@EdJoPaTo could you throw these changes into one of your larger bots and report if it caused any issues? :)

**Review by EdJoPaTo — APPROVED** [review]
I use `grammyjs/types` normally so I was a bit sceptical about the simple install. Does it use the different types library then? VSCode Hover suggests that it does.

For anyone interested: I threw the following command into a bunch of my repos and none failed with this PR.

```bash
npm i grammyjs/types#narrow-message-updates && npm test
```

**Comment by KnorpelSenf** [comment]
Sounds pretty good. I assume that this works then. Just to be sure: do your tests perform type checks?

**Comment by EdJoPaTo** [comment]
Yes: `tsc` and type aware lints (`xo`).

**Comment by KnorpelSenf** [comment]
Awesome, thanks! I'll merge then :)

**Pull request merged**
